---
- name: Reload workspace vars
  ansible.builtin.include_vars:
    dir: "{{ workspace_group_vars_dir }}"
    ignore_unknown_extensions: true

- name: Create selection databases
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ item }}-database-creation"
        namespace: "{{ namespace }}"
      spec:
        ttlSecondsAfterFinished: 120
        template:
          spec:
            containers:
              - name: "{{ item }}-database-creation"
                image: bitnami/postgresql:latest
                command: ["createdb"]
                args:
                  [
                    "-h",
                    "{{ service_names.postgresql }}",
                    "-U",
                    "postgres",
                    "{{ item }}",
                  ]
                env:
                  - name: PGPASSWORD
                    value: "{{ postgresql_init_content.admin_password }}"
            restartPolicy: Never
  with_items:
    - peatio
    - barong
    - kouda
    - quantex
