---
- name: Check postgresql is inited
  ansible.builtin.stat:
    path: "{{ workspace_secrets_dir }}/postgresql_init_content.yml"
  register: init_result
  no_log: true
  run_once: true
  become: false

- name: Init postgresql
  when: not init_result.stat.exists
  block:
    - name: Set password for postgresql
      ansible.builtin.set_fact:
        postgresql_init_content:
          admin_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits,punctuation') }}"

    - name: Store postgresql password
      ansible.builtin.copy:
        dest: "{{ workspace_secrets_dir }}/postgresql_init_content.yml"
        content: |-
          ---
          {{ {'postgresql_init_content': postgresql_init_content} | to_nice_yaml }}
        mode: 0600
      become: false
      delegate_to: localhost
