---
- name: Init postgresql password secret
  ansible.builtin.include_tasks: _init.yml

- name: Deploy postgresql using Helm chart
  ansible.builtin.include_tasks: _deploy.yml

- name: User creation
  ansible.builtin.include_tasks: _user_creation.yml
  with_items:
    - name: barong_manager
      database: barong
    - name: peatio_manager
      database: peatio
    - name: kouda_manager
      database: kouda
    - name: quantex_manager
      database: quantex
