---
- name: Create jwt private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ __jwt_private_key_file }}"

- name: Generate jwt public key from private key
  community.crypto.openssl_publickey:
    path: "{{ __jwt_public_key_file }}"
    privatekey_path: "{{ __jwt_private_key_file }}"

- name: Create event api jwt private key (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ __event_api_jwt_private_key }}"

- name: Generate event api jwt public key from private key
  community.crypto.openssl_publickey:
    path: "{{ __event_api_jwt_public_key }}"
    privatekey_path: "{{ __event_api_jwt_private_key }}"

- name: Create jwt private key secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', './secret.yml.j2') }}"
