---
- name: Create a istio-system namespace
  kubernetes.core.k8s:
    name: istio-system
    api_version: v1
    kind: Namespace
    state: present

- name: Patch istio-system namespace with istio-injection
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: istio-system
        labels:
          "istio-injection": enabled

- name: Add istio chart repo
  kubernetes.core.helm_repository:
    name: istio
    repo_url: https://istio-release.storage.googleapis.com/charts

- name: Deploy latest version of istio/base chart
  kubernetes.core.helm:
    name: istio-base
    chart_ref: istio/base
    chart_version: 1.17.2
    release_namespace: istio-system

- name: Deploy latest version of istio/istiod chart
  kubernetes.core.helm:
    name: istiod
    chart_ref: istio/istiod
    chart_version: 1.17.2
    release_namespace: istio-system

- name: Deploy latest version of istio/gateway chart
  kubernetes.core.helm:
    name: istio-ingress
    chart_ref: istio/gateway
    chart_version: 1.17.2
    release_namespace: istio-ingressgateway
