---
- name: Copy charts source
  ansible.builtin.copy:
    src: "charts/{{ item }}"
    dest: "{{ workspace_charts_dir }}/"
  delegate_to: localhost
  become: false
  run_once: true
  with_items:
    - z-dax
    - peatio

- name: compress all the files in tar.gz
  community.general.archive:
    path: "{{ workspace_charts_dir }}/peatio"
    dest: "{{ workspace_charts_dir }}/z-dax/charts/peatio.tgz"
    format: gz
  become: false
  run_once: true

- name: Deploy local z-dax chart
  kubernetes.core.helm:
    name: "{{ workspace }}"
    chart_ref: "{{ workspace_charts_dir }}/z-dax"
    release_namespace: "{{ namespace }}"
    values:
      global:
        svcPorts:
          deposit_address: "{{ service_ports.deposit_address }}"
          withdraw: "{{ service_ports.withdraw }}"
          trade_executor: "{{ service_ports.trade_executor }}"
          order_processor: "{{ service_ports.order_processor }}"
          matching: "{{ service_ports.matching }}"
          code: "{{ service_ports.code }}"
          p2p: "{{ service_ports.p2p }}"
          conversation: "{{ service_ports.conversation }}"
          notify: "{{ service_ports.notify }}"
          quantex_runner: "{{ service_ports.quantex_runner }}"
