---
- name: Copy charts source
  ansible.builtin.copy:
    src: "charts/{{ item }}"
    dest: "{{ workspace_charts_dir }}/"
  delegate_to: localhost
  become: false
  run_once: true
  with_items:
    - peatio
    - barong
    - kouda
    - z-dax

- name: compress subcharts files into tar.gz
  community.general.archive:
    path: "{{ workspace_charts_dir }}/{{ item }}"
    dest: "{{ workspace_charts_dir }}/z-dax/charts/{{ item }}.tgz"
    format: gz
  become: false
  run_once: true
  with_items:
    - peatio
    - barong
    - kouda

- name: Deploy local z-dax chart
  kubernetes.core.helm:
    name: "{{ workspace }}"
    chart_ref: "{{ workspace_charts_dir }}/z-dax"
    release_namespace: "{{ namespace }}"
    values:
      global:
        domain: "{{ external_domain }}"
      gatewayServices:
        - name: barong-api
          port: "{{ service_ports.barong_api }}"
          match:
            uri:
              prefix: /api/v2/auth
          rewrite:
            uri: /api
        - name: peatio-api
          port: "{{ service_ports.peatio_api }}"
          match:
            uri:
              prefix: /api/v2/trade
          rewrite:
            uri: /api
        - name: kouda-api
          port: "{{ service_ports.kouda_api }}"
          match:
            uri:
              prefix: /api/v2/kouda
          rewrite:
            uri: /api
      peatio:
        serviceAccount:
          name: z-dax
        service:
          ports:
            api: "{{ service_ports.peatio_api }}"
            deposit_address: "{{ service_ports.deposit_address }}"
            withdraw: "{{ service_ports.withdraw }}"
            trade_executor: "{{ service_ports.trade_executor }}"
            order_processor: "{{ service_ports.order_processor }}"
            matching: "{{ service_ports.matching }}"
            p2p: "{{ service_ports.p2p }}"
            conversation: "{{ service_ports.conversation }}"
            notify: "{{ service_ports.notify }}"
            grpc: "{{ service_ports.peatio_grpc }}"
      barong:
        authz:
          jwt_secret:
            name: "{{ jwt_secret.name }}"
            file: "{{ jwt_secret.file }}"
        serviceAccount:
          name: z-dax
        service:
          ports:
            api: "{{ service_ports.barong_api }}"
            authz: "{{ service_ports.barong_authz }}"
            code: "{{ service_ports.code }}"
            activity_recorder: "{{ service_ports.activity_recorder }}"
      kouda:
        serviceAccount:
          name: z-dax
        service:
          port: "{{ service_ports.kouda_api }}"
      quantex:
        serviceAccount:
          name: z-dax
        service:
          ports:
            port: "{{ service_ports.quantex_api }}"
            runner: "{{ service_ports.quantex_runner }}"
