---
- name: Create global secret for z-dax
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ workspace }}-global"
        namespace: "{{ namespace }}"
      data:
        barongVaultToken: "{{ barong_vault_token | b64encode }}"
        peatioVaultToken: "{{ peatio_vault_token | b64encode }}"
        peatioCryptoVaultToken: "{{ peatio_vault_token | b64encode }}"
        kaigaraVaultToken: "{{ kaigara_vault_token | b64encode }}"
        quantexVaultToken: "{{ quantex_vault_token | b64encode }}"
        quantexRunnerVaultToken: "{{ quantex_runner_vault_token | b64encode }}"
