apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postgres.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: postgres
