apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
{{- range $key, $value := .Values.service.ports }}
    - name: {{ $key | quote }}
{{ toYaml $value | indent 6 }}
{{- end }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
