apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gateways:
    - {{ .Values.global.ingressGatewayName | quote }}
  hosts:
    - "postgres"
  tcp:
    - match:
      - port: {{ .Values.ingressGateway.port }}
      route:
        - destination:
            host: {{ .Values.service.name | quote }}
            port:
              number: {{ .Values.ingressGateway.targetPort }}
