apiVersion: v1
kind: Service
metadata:
  name: {{ include "barong.fullname" . }}-authz
  labels:
    {{- include "barong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.authz }}
      targetPort: authz-api
      protocol: TCP
      name: {{ .Values.service.name }}-authz
  selector:
    {{- include "barong.selectorLabels" . | nindent 4 }}
