{{- $values := .Values }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "barong.fullname" . }}-daemon
  labels:
    {{- include "barong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $streamDaemon := $values.streamDaemons }}
{{- $port := (index $values.global.svcPorts $streamDaemon) }}
    - port: {{ $port }}
      targetPort: {{ $streamDaemon | replace "_" "-" }}
      protocol: TCP
      name: {{ $streamDaemon | replace "_" "-" }}
{{- end }}
  selector:
    {{- include "barong.selectorLabels" . | nindent 4 }}
