apiVersion: v1
kind: Service
metadata:
  name: {{ include "barong.fullname" . }}
  labels:
    {{- include "barong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "barong.selectorLabels" . | nindent 4 }}
