apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: tcp
  selector:
    {{- include "schema-registry.selectorLabels" . | nindent 4 }}
