apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "peatio.fullname" . }}
  labels:
    {{- include "peatio.labels" . | nindent 4 }}
data:
  abilities.yml: |-
    roles:
      - superadmin
      - admin
      - technical
      - accountant
      - compliance
      - support
      - member

    admin_permissions:
      superadmin:
        manage:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Operations::Revenue
          - Member
          - Account
          - Beneficiary
          - DepositAddress
          - Deposit
          - Withdraw
          - WithdrawLimit
          - Blockchain
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - TradingFee
          - Wallet
          - Adjustment
          - InternalTransfer
          - WhitelistedSmartContract
          - Order
        read:
          - Trade
          - Statistic
      admin:
        manage:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Operations::Revenue
          - Member
          - Account
          - Beneficiary
          - PaymentAddress
          - Deposit
          - Withdraw
          - WithdrawLimit
          - Blockchain
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - TradingFee
          - Wallet
          - Adjustment
          - InternalTransfer
          - WhitelistedSmartContract
          - Order
        read:
          - Trade
          - Statistic
      technical:
        read:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Trade
          - Order
          - Member
          - InternalTransfer
        manage:
          - WithdrawLimit
          - Blockchain
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - TradingFee
          - Wallet
          - Statistic
      accountant:
        read:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Operations::Revenue
          - Member
          - Account
          - Beneficiary
          - PaymentAddress
          - Deposit
          - Withdraw
          - WithdrawLimit
          - Blockchain
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - TradingFee
          - Wallet
          - Trade
          - Order
          - Adjustment
          - InternalTransfer
        manage:
          - Deposits::Fiat
          - Adjustment
      compliance:
        read:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Member
          - Account
          - Beneficiary
          - PaymentAddress
          - Deposit
          - Withdraw
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - Trade
          - Order
      support:
        read:
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Member
          - Account
          - Beneficiary
          - PaymentAddress
          - Deposit
          - Withdraw
          - Currency
          - BlockchainCurrency
          - Engine
          - Market
          - Trade
          - Order
          - InternalTransfer
      reporter:
        read:
          - Operations::Revenue
          - Operations::Account
          - Operations::Asset
          - Operations::Expense
          - Operations::Liability
          - Deposit
          - Withdraw
          - Currency
          - BlockchainCurrency
          - Wallet
          - Blockchain

  markets.yml: |-
    - id: btcusdt
      base_unit: btc
      quote_unit: usdt
      amount_precision: 5
      price_precision: 2
      total_precision: 5
      state: enabled
      min_price: 10
      max_price: 0
      min_amount: 0.0001
      position: 1

    - id: ethusdt
      base_unit: eth
      quote_unit: usdt
      amount_precision: 4
      price_precision: 2
      total_precision: 5
      state: enabled
      min_price: 10
      max_price: 0
      min_amount: 0.001
      position: 2

    - id: bnbusdt
      base_unit: bnb
      quote_unit: usdt
      amount_precision: 3
      price_precision: 1
      total_precision: 2
      state: enabled
      min_price: 10
      max_price: 0
      min_amount: 0.01
      position: 3

    - id: trxusdt
      base_unit: trx
      quote_unit: usdt
      amount_precision: 1
      price_precision: 5
      total_precision: 3
      state: enabled
      min_price: 0.0001
      max_price: 0
      min_amount: 5
      position: 4

    - id: dogeusdt
      base_unit: doge
      quote_unit: usdt
      amount_precision: 0
      price_precision: 5
      total_precision: 3
      state: enabled
      min_price: 0.00001
      max_price: 0
      min_amount: 5
      position: 5

  currencies.yml: |-
    - id: usdt
      name: Tether
      status: enabled
      precision: 2
      position: 1

    - id: eth
      name: Ethereum
      status: enabled
      precision: 8
      position: 2

    - id: btc
      name: Bitcoin
      status: enabled
      precision: 8
      position: 3

    - id: bnb
      name: Binance Coin
      status: enabled
      precision: 8
      position: 4

    - id: trx
      name: Tron
      status: enabled
      precision: 8
      position: 5

    - id: doge
      name: Dogecoin
      status: enabled
      precision: 8
      position: 6

  accounts.yml: |-
    - code:           102
      type:           asset
      kind:           main
      description:    Main Digital Assets Account
      scope:          platform

    - code:           202
      type:           liability
      kind:           main
      description:    Main Digital Asset Spot Liabilities Account
      scope:          member

    - code:           212
      type:           liability
      kind:           locked
      description:    Locked Digital Asset Spot Liabilities Account
      scope:          member

    - code:           222
      type:           liability
      kind:           main
      description:    Main Digital Asset P2P Liabilities Account
      scope:          member

    - code:           232
      type:           liability
      kind:           locked
      description:    Locked Digital Asset P2P Liabilities Account
      scope:          member

    - code:           302
      type:           revenue
      kind:           main
      description:    Main Digital Asset Revenues Account
      scope:          platform

    - code:           402
      type:           expense
      kind:           main
      description:    Main Digital Asset Expenses Account
      scope:          platform
