{{- $labels := include "peatio.labels" . }}
{{- $releaseName := .Release.Name }}
{{- $env := include "daemons.env" . }}
{{- $image := printf "%s:%s" .Values.image.repository .Values.image.tag }}
{{- $values := .Values }}

{{- range $daemon := .Values.daemons }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peatio.fullname" . }}-daemon-{{ $daemon | replace "_" "-" }}
  labels:
    {{- $labels | nindent 4 }}
    daemon: {{ $daemon | replace "_" "-" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "peatio.name" . }}-daemon
      daemon: {{ $daemon | replace "_" "-" }}
      release: {{ $releaseName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "peatio.name" . }}-daemon
        daemon: {{ $daemon | replace "_" "-" }}
        release: {{ $releaseName }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "z-dax"
        vault.hashicorp.com/agent-inject-secret-config: "postgres/creds/z-dax_peatio"
        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "postgres/creds/z-dax_peatio" -}}
            export DATABASE_USER="{{ .Data.username }}"
            export DATABASE_PASS="{{ .Data.password }}"
          {{- end }}`}}
    spec:
      {{- with $values.image.PullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ $daemon | replace "_" "-" }}-daemon"
          image: {{ $image }}
          imagePullPolicy: {{ $values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - source /vault/secrets/config && kaigara ./{{ $daemon }}
          resources:
            {{- toYaml $values.resources | nindent 12 }}
          env:
            {{ $env | nindent 12 }}
      serviceAccountName: z-dax
{{- end }}
