{{- $values := .Values }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peatio.fullname" . }}-daemon
  labels:
    {{- include "peatio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $streamDaemon := $values.streamDaemons }}
{{- $port := (index $values.service.ports $streamDaemon) }}
    - port: {{ $port }}
      targetPort: {{ $streamDaemon | replace "_" "-" | trunc 15 }}
      protocol: TCP
      name: {{ $streamDaemon | replace "_" "-" }}
{{- end }}
  selector:
    {{- include "peatio.selectorLabels" . | nindent 4 }}
