---
- name: Create a kiali-operator namespace
  kubernetes.core.k8s:
    name: kiali-operator
    api_version: v1
    kind: Namespace
    state: present

- name: Add kiali chart repo
  kubernetes.core.helm_repository:
    name: kiali
    repo_url: https://kiali.org/helm-charts

- name: Deploy latest version of kiali-operator chart
  kubernetes.core.helm:
    name: kiali-operator
    chart_ref: kiali/kiali-operator
    chart_version: 1.68.0
    release_namespace: kiali-operator
    values:
      cr:
        create: true
        name: kiali
        namespace: istio-system
        spec:
          external_services:
            grafana:
              in_cluster_url: http://kube-prometheus-stack-grafana.monitoring
              dashboards:
                - name: "Istio Service Dashboard"
                - name: "Istio Workload Dashboard"
                - name: "Istio Mesh Dashboard"
                - name: "Istio Control Plane Dashboard"
                - name: "Istio Performance Dashboard"
                - name: "Istio Wasm Extension Dashboard"
            prometheus:
              url: http://kube-prometheus-stack-prometheus.monitoring:9090
              health_check_url: http://kube-prometheus-stack-prometheus.monitoring:9090/-/healthy
            tracing:
              enabled: true
              in_cluster_url: http://jaeger-collector.monitoring:16685/jaeger
              use_grpc: true
          auth:
            strategy: anonymous
          login_token:
            signing_key: PASSWORD
          deployment:
            istio_namespace: istio-system
            accessible_namespaces:
              - "**"
            ingress:
              enabled: true
              class_name: nginx
          server:
            web_fqdn: kiali.k8s-learn.com
            web_schema: http
            web_port: 80
            web_root: /
