---
- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present

- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: jaegertracing
    repo_url: https://jaegertracing.github.io/helm-charts

- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy latest version of kube-prometheus-stack chart
  kubernetes.core.helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 45.29.0
    release_namespace: monitoring
    values:
      alertmanager:
        enabled: false

      grafana:
        enabled: true
        defaultDashboardsEnabled: true
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.k8s-learn.com

      kube-state-metrics:
        enabled: true

      kubeControllerManager:
        enabled: false

      kubeScheduler:
        enabled: false

      kubeProxy:
        enabled: false

      ## Deploy a Prometheus instance
      ##
      prometheus:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus.k8s-learn.com
        prometheusSpec:
          ruleSelectorNilUsesHelmValues: false
          serviceMonitorSelectorNilUsesHelmValues: false
          podMonitorSelectorNilUsesHelmValues: false

          retention: 6h

          additionalScrapeConfigs:
            - job_name: "istiod"
              kubernetes_sd_configs:
                - role: endpoints
                  namespaces:
                    names:
                      - istio-system
              relabel_configs:
                - source_labels:
                    [
                      __meta_kubernetes_service_name,
                      __meta_kubernetes_endpoint_port_name,
                    ]
                  action: keep
                  regex: istiod;http-monitoring

            - job_name: "envoy-stats"
              metrics_path: /stats/prometheus
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_container_port_name]
                  action: keep
                  regex: ".*-envoy-prom"

- name: Deploy latest version of jaeger chart
  kubernetes.core.helm:
    name: jaeger
    chart_ref: jaegertracing/jaeger
    chart_version: 0.69.1
    release_namespace: monitoring
    values:
      allInOne:
        enabled: true
        tag: 1.37.0

      storage:
        type: none

      provisionDataStore:
        cassandra: false

      agent:
        enabled: false

      collector:
        enabled: false

      query:
        enabled: false
