---
- name: Stage 3 - Load secret to kaigara using vault
  hosts: localhost
  become: false
  gather_facts: false
  pre_tasks:
    - name: Reload workspace vars
      ansible.builtin.include_vars:
        dir: "{{ workspace_group_vars_dir }}"
        ignore_unknown_extensions: true
  vars:
    kaigara_vault_addr: "http://vault.{{ internal_domain }}"
  roles:
    - kaisave
