apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "adminer.fullname" . }}-gateway
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "adminer.{{ .Values.global.externalHostname }}"
