{{- if .Values.enableMigration }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "barong.name" . }}-prepare-db
  labels:
    {{- include "barong.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ include "barong.fullname" . }}
        component: barong
    spec:
      {{- with .Values.image.PullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: prepare-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - kaigara ./barong migration && kaigara ./barong seed
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretPrefix }}-global
                  key: barongVaultToken
            {{ include "prepare.env" . | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config/seeds.yml
              subPath: seeds.yml
      volumes:
        - name: config
          configMap:
            name: {{ template "barong.fullname" . }}
{{- end }}
